### PR TITLE
Pdelong42/cleanup

### PR DESCRIPTION
**Pull request by pdelong42**
This is my first pass at making this code work again.  It isn't as polished as it could be, and there will certainly be more refinements later.  But I've gotten it to a point where I can render graphs again, and that's a milestone.

Naturally, use your judgement on whether you think this is worthy of merging (or if you'd rather wait until further improvements from me - but I make no promises on how quickly I can get to them).

### CODE REVIEW

**Comment by maoe** [comment]
Great work.

I guess I'm happy to hand off this project to someone as I'm not a Clojure user.

What license are you thinking to apply? If the new license is fine for the Clojure community and my copyright remains with limited years (2010-2015. You can add yourself with a new copyright starting from 2015), I can transfer the ownership to you.

What do you think?

**Comment by pdelong42** [comment]
That sounds great to me.  I would be happy to take on ownership of the
project.

The copyright idea sounds good.  If that commit comes from you, after you
merge the pull-request, but before you transfer ownership, then I think
that makes the most sense.

I'm not sure whether I would want to even retain copyright for myself, from
this point forward.  But I would need to look into what makes the most
sense, regarding what copyright law says.  I guess it can't hurt for me to
claim copyright for at-least the 2016 period.

As for the license, I was thinking of using the Eclipse Public license,
since that's what most of the rest of the Clojure community seems to be
using.  But I'm fine with keeping the New BSD license.  I'm not terribly
picky, as long as it's something that is fairly permissive and encourages
contributions from others.

Thanks again for the time and energy you've put into this already.  You
gave me something to build on, and learn from.  Just let me know what the
next steps are when you can.

Thanks,
Paul DeLong

**Comment by pdelong42** [comment]
Let me know if you're still amenable to transferring ownership.  I'm still willing to take over responsibility for the project.  If you've been busy, then no worries.  I'm in no particular hurry, just give me a quick heads-up.

I've never done an ownership transfer of a repository.  Do you know how this works?  Do I need to delete my fork before you transfer ownership to me (to avoid a name collision)?  If I delete my fork before you merge my changes, does my pull-request disappear?

**Comment by maoe** [comment]
Sorry for the late response. I think I can work on this during the new year holidays. Basically I'm going to merge this PR then transfer the repository to you. This is my first transfer so I'm not sure about the questions you have.

**Comment by pdelong42** [comment]
Then the process is new to both of us. :-)

When I get a moment, I should look and see if they answer my questions in a FAQ list somewhere.  If I learn anything, I'll let you know.

By the way, sorry about my noisy commit history.  I only just yesterday learned how to squash commits (and now I see why that's such a useful feature).

**Comment by maoe** [comment]
Would you like to squash commits? If so, please do. I'll merge them after that.

**Comment by pdelong42** [comment]
It's okay.  I think it would be too much trouble at this point.  Plus I'm not crazy about modifying commit history once it's been pushed to someplace public.  So the merge can happen any time you're able.

**Comment by maoe** [comment]
I've just merged this PR and updated the copyright in the README.

Regarding the ownership transfer, [the target account must not have a repository with the same name, or a fork in the same network](https://help.github.com/articles/transferring-a-repository/). So you need to delete the fork first. Let me know when you've done it.

**Comment by pdelong42** [comment]
Okay, I've deleted my fork.

It will interesting to see how this goes, since I've never transferred a
repository before.

**Comment by maoe** [comment]
Alright. I'll give it a shot now.

**Comment by maoe** [comment]
The status line on the Settings page says:

> This repository is being transferred to @pdelong42.

Let's see how it goes.

**Pull request merged**
